name: CI

on:
  workflow_dispatch: {}
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.6

      - name: debug git diff
        run: |
          git --version
          pwd
          ls -l
          git diff-tree 06658847db56edc46b4b7d60b799313503468d32 0c94dea141ba2d472ad7d19abf201059cb476f1e -r --abbrev=40 --full-index -M --raw --no-color

      - name: Unit tests
        run: |
          python -mvenv venv
          source venv/bin/activate
          pip install -U cython
          pip install -r dev_requirements.txt
          pip install -r requirements.txt
          pytest tests/

      - name: Snyk package deps scan
        uses: snyk/actions/python@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
